fdasj

diff --git a/Scripts/git_hooks/pre-commit b/Scripts/git_hooks/pre-commit
--- a/Scripts/git_hooks/pre-commit
+++ b/Scripts/git_hooks/pre-commit
@@ -1,7 +1,7 @@
 #!/bin/sh
 
 HOME_DIR=$(git rev-parse --show-toplevel)
-DIFF_FILES =$(git diff --exit-code --name-only --diff-filter=ACM "*.cs")
+DIFF_FILES=$(git diff --exit-code --cached --name-only --diff-filter=ACM -- "*.cs")
 
 echo "Auto formatting for the project by dotnet-format"
 
@@ -10,6 +10,10 @@ if [ -z "${FILES}" ]; then
 else
   echo "The following source codes are modified"
   dotnet format ${HOME_DIR}/*.sln
+  if [ $? -ne 0 ]; then
+    echo "Dotnet format failed, please fix code and recommit"
+    exit 1
+  fi
 fi
 
 exit 0
